name: "Terraform PROD"

on:

  push:
    branches:
      - main
    paths:
      - "Infra-repo/**"

  pull_request:
    branches:
      - main
    paths:
      - "Infra-repo/**"

  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:

  terraform:
    uses: ./.github/workflows/terraform-reusable.yml

    with:
      environment: prod
      terraform_version: "1.15.3"
      tflint_version: "v0.52.0"
      working_directory: "./Infra-repo/root"
      tfvars_file: "../environments/prod/prod.tfvars"
      run_apply: ${{ github.event_name == 'push' }}
      trivy_exit_code: "1"

    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}